(function(){
'use strict';
var V='1.1.0',STORE={logs:'urgez_logs_v1',notes:'urgez_notes_v1',holds:'urgez_holds_v1'};
var C={
sweets:{e:'🍫',n:'お菓子',sub:'爆食い・夜のお菓子',impact:'明日の腹と仕事まで持っていかれる。',desc:'お菓子ゼロが目的やなく、爆食いを止める。昨日みたいな腹痛・下痢・ガスまで行く量は割に合わん。',why:['腹痛・下痢・ガスで仕事を邪魔されたくない','食べすぎで体重管理を崩したくない','肌を整えたいのに夜の爆食いを続けたくない','ダラダラ食いを減らして歯も守りたい','お菓子に金と判断を持っていかれたくない'],loss:'8/26に爆食い→8/27朝は腹痛・下痢・ガスで何度もトイレ。Diaryでも夜のお菓子と体重増加を何度も反省。',ideal:'食べる時も量を自分で決めて、その1回で終われる。',rule:['袋ごとの爆食い・夜のダラダラ食いはしない','食べる量を先に決め、その1回で終わる','腹や翌日の仕事に響きそうならやめる'],stop:'🛡 今は食べない',allow:'🍫 1回分で終われるならOK',hold:600000,faith:'Qur’an 7:200 · 誘惑にそのまま従わず一度止まる'},
tobacco:{e:'🚬',n:'タバコ',sub:'1人・常習はNG',impact:'嫌なのは「たまの1本」より、依存が日常に戻ること。',desc:'友達といる特別な1日まで全部禁止にせず、1人・買い置き・連日へ広げない境界を先に決める。',why:['また「吸いたい」に予定を決められたくない','1人で吸う習慣を作りたくない','臭いを服・部屋・息に残したくない','金を払って次の欲求を作りたくない','友達の日が終わったらタバコも終わりにしたい'],loss:'Diaryに「久々吸ったけどくそまずかった」。嫌なのは味より、そこから普段の欲求へ戻ること。',ideal:'普段は吸わない。友達との特別な日だけに閉じ込め、翌日に持ち越さない。',rule:['友達と一緒にいる特別な日だけ','1人の時は吸わない','自分用に買い置きしない','翌日・連日へ持ち越さない'],note:'これは依存・常習化を防ぐ個人ルール。条件内でも喫煙が健康上安全になるわけではない。',stop:'🛡 今日は吸わない',allow:'✅ 友達と今日だけならOK',hold:600000,faith:'Qur’an 7:200 · 欲望に自動で従わず自分で選ぶ'},
sns:{e:'📱',n:'SNS',sub:'無目的スクロール',impact:'目的なしで開いたら、時間だけ消える。',desc:'必要な投稿を見るSNSと、指が勝手に開くSNSは別。見る目的が言えるかだけ確認する。',why:['無意識スクロールに時間を取られたくない','制作・英語・人との時間に集中を戻したい','寝る前の「もう少し」で睡眠を削りたくない','見たい物がある時だけ開ける状態にしたい'],loss:'Diaryでも「SNSはマジにやめれな…」と反省。残るのは見た内容より消えた時間。',ideal:'目的がある時だけ開き、見終わったら閉じる。',rule:['何を見るか1つ言える時だけ開く','目的の物を見たらホームTLへ流れない','終わったらその場で閉じる'],stop:'🛡 今は開かない',allow:'✅ 見る目的があるならOK',hold:600000,faith:'Qur’an 7:200 · 注意を奪う誘惑にも一回止まる'},
shopping:{e:'🛒',n:'買いすぎ',sub:'欲しい→条件確認',impact:'欲しい＝ダメじゃない。条件を通った物だけ買う。',desc:'香水みたいに本当に欲しい物まで全部止める必要はない。衝動を24時間切って、用途・重複・予算を通ったら買っていい。',why:['無駄な買い物を減らして貯金・投資へ回したい','部屋の物を増やしすぎたくない','安い・欲しいだけで即決したくない','本当に使う一軍だけ残したい','買った後の「いらんかった」を減らしたい'],loss:'Diaryでも「買いすぎ」「貯金しよう」「今年やらない＝無駄な買い物」と反省。問題は買うこと自体じゃなく、条件なしの即決。',ideal:'欲しい→24時間保留→まだ欲しい＋用途明確＋重複なし＋予算内なら買う。',rule:['24時間置いてもまだ欲しい','使う場面・目的が具体的','似た役割の物があるなら置換か明確な違いがある','貯金・投資や必要支出を崩さない'],stop:'⏳ 24時間保留する',allow:'✅ 条件を満たした｜買ってOK',hold:86400000,after:true,faith:'Qur’an 7:200 · 衝動と判断の間に時間を置く'},
porn:{e:'🔞',n:'ポルノ',sub:'暇・衝動で見る',impact:'見たいのか、刺激に引っ張られてるだけか。',desc:'罪悪感で罰するより、暇・ストレス・惰性で自動的に開く流れを止める。',why:['刺激を求めて無意識に開く癖を弱くしたい','時間と集中を持っていかれたくない','より強い刺激を探し続ける使い方を避けたい','現実の人間関係より画面の刺激を優先したくない'],loss:'Diaryで繰り返しの実害まではまだ確認できていない。まず「自動で開かない」を目標にする。',ideal:'衝動に自動で流されず、見ない選択を普通にできる。',rule:['暇・ストレス・惰性で自動的に開かない','より強い刺激を探し続ける流れに入らない','現実の時間・関係・睡眠を削らない'],stop:'🛡 今は見ない',hold:600000,faith:'Qur’an 24:30 · 視線と欲望を自分で制御する判断軸'},
alcohol:{e:'🍺',n:'酒',sub:'1人・習慣はNG',impact:'嫌なのは、酒が「いつもの行動」になること。',desc:'個人ルールでは友達との特別な日だけ。1人飲み・曜日固定・ストレス飲みへ広げない。',why:['飲酒を曜日・ストレスの自動習慣にしたくない','1人で飲む習慣を作りたくない','飲んだ後のぼーっとした感じを避けたい','翌日の時間と判断力を残したい','イスラムの判断軸も忘れたくない'],loss:'Diaryに「酒のあとはぼーとする」。Islamzでも「金曜夜＝酒」の習慣化が怖いと気づき、飲まなかった経験を記録。',ideal:'普段は飲まない。飲酒が日常やストレス対処にならない。',rule:['kedy個人ルールでは友達との特別な日だけ','1人では飲まない','曜日固定・ストレス解消の酒にしない','翌日まで続けない'],note:'イスラム上は、友達と一緒でも酒が許可になるわけではない。これは宗教上の許可ではなく、常習化させないための個人ルール。',stop:'🛡 今日は飲まない',allow:'✅ 個人ルール内なら記録',hold:0,faith:'Qur’an 5:90–91 · 酒（khamr）は避ける対象'},
pork:{e:'🐷',n:'豚',sub:'豚肉・豚由来',impact:'便利さより、選びたい生活の軸を優先する。',desc:'体に悪いからではなく、イスラムを生活で理解・実践するなら「選べる場面では避ける」を積み上げる。',why:['Halal / Haramを知識だけで終わらせたくない','豚を避ける判断を日常で自然にしたい','外食でも一度確認する癖をつけたい','「まあいいか」で自分の軸を崩したくない'],loss:'体調の罰を避ける項目ではない。惰性の「まあいいか」に流される回数を減らす。',ideal:'豚が入ってると分かったら、迷わず別の物を選べる。',rule:['豚と分かっているなら別の物を選ぶ','「付き合い」「まあいいか」だけでは崩さない','必要性の例外と日常の便利さは分ける'],note:'イスラムの基準では豚肉は禁じられる食物。日常の「条件内ならOK」ボタンは置かない。',stop:'🛡 別の物を選ぶ',hold:0,faith:'Qur’an 2:173 / 5:3 · 豚肉は禁じられる食物'}
};
var ORDER=['sweets','tobacco','sns','shopping','porn','alcohol','pork'],sel=null,timer=null;
function rj(k,d){try{var v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch(e){return d}}
function wj(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function logs(){var x=rj(STORE.logs,[]);return Array.isArray(x)?x:[]}
function notes(){var x=rj(STORE.notes,{});return x&&typeof x==='object'?x:{}}
function holds(){var x=rj(STORE.holds,{});return x&&typeof x==='object'?x:{}}
function note(id){var x=notes()[id];return x&&typeof x==='object'?x:{why:'',rule:'',win:''}}
function hend(id){var x=holds()[id];return x&&typeof x==='object'?Number(x.until||0):Number(x||0)}
function mk(ts){var d=new Date(ts||Date.now());return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function fd(ts){var d=new Date(ts);return (d.getMonth()+1)+'/'+d.getDate()+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function stats(id){var a=logs().filter(x=>mk(x.ts)===mk()&&(!id||x.cat===id)),g=a.filter(x=>x.result==='stop'||x.result==='allow').length;return{t:a.length,g:g,r:a.length?Math.round(g/a.length*100):null}}
var extra=`<style id="urgez-v11">.rule{border-color:rgba(50,217,233,.2);background:linear-gradient(145deg,rgba(50,217,233,.075),rgba(20,22,28,.78))}.rule-list{display:grid;gap:7px}.rule-item{display:grid;grid-template-columns:19px 1fr;gap:7px;font-size:11px;line-height:1.42;color:#e8f5f7}.rule-item:before{content:"✓";color:var(--green);font-weight:950}.rule-note{margin-top:8px;padding-top:8px;border-top:1px solid rgba(255,255,255,.06);color:var(--muted);font-size:9px;line-height:1.45}.rule-state{display:inline-flex;margin-top:8px;padding:6px 9px;border-radius:999px;border:1px solid rgba(255,173,50,.2);background:rgba(255,173,50,.07);color:var(--amber);font-size:9px;font-weight:900}.rule-state.ready{border-color:rgba(87,223,140,.25);background:rgba(87,223,140,.08);color:var(--green)}.allow-btn{display:none;width:100%;min-height:50px;margin-top:8px;border:1px solid rgba(87,223,140,.28);border-radius:18px;background:rgba(87,223,140,.10);color:#dff9e9;font-size:13px;font-weight:900}.allow-btn.show{display:block}.allow-btn:disabled{opacity:.38}</style>`;
document.head.insertAdjacentHTML('beforeend',extra);
document.body.innerHTML=`<header><div class="brand"><h1>Urge<span>z</span></h1><span class="version">v1.1 · 2026.08.27</span></div><button class="icon-btn" id="menuBtn">···</button></header>
<main id="homeView" class="view active"><div class="eyebrow">STOP THE AUTO-PILOT</div><h2 class="question">いま何に負けそう？</h2><p class="sub">禁止か許可かを考えんでええ。先に決めた条件を見る。</p><div class="urge-grid" id="urgeGrid"></div><div class="statbar"><div class="stat"><b id="good">0</b><span>GOOD</span></div><div class="stat"><b id="checks">0</b><span>CHECKS</span></div><div class="stat"><b id="rate">—</b><span>RATE</span></div></div><div class="recent-win" id="recent"><b>WIN</b>　まだログなし。</div></main>
<main id="detailView" class="view"><div class="detail-top"><button class="icon-btn" id="back">‹</button><h2 id="title"></h2><button class="icon-btn" id="detailMenu">···</button></div><section class="impact"><div class="impact-kicker">いま止める理由</div><h3 id="impact"></h3><p id="desc"></p></section><section class="faith-strip"><div class="arabic">Aʿūdhu billāhi min ash-shayṭānir-rajīm</div><p>「呪われたShayṭānからAllahに守りを求めます」<br>誘惑＝命令やない。一回止まって、自分で選ぶ。</p><span class="faith-ref" id="faith"></span></section><section class="block rule"><div class="block-head"><b>MY RULE｜OKになる条件</b><span>自分の上限</span></div><div class="rule-list" id="rules"></div><div class="rule-state" id="state" hidden></div><div class="rule-note" id="note" hidden></div></section><section class="block"><div class="block-head"><b>WHY｜なんで変えたい？</b><span>自分の目的</span></div><div class="reasons" id="whys"></div></section><section class="block loss"><div class="block-head"><b>REAL LOSS｜また欲しい？</b><span>実体験</span></div><div id="loss"></div></section><section class="block ideal"><div class="block-head"><b>IDEAL｜欲しい状態</b><span>その先</span></div><div id="ideal"></div></section><section class="block custom-win" id="winBlock" hidden><div class="block-head"><b>REAL WIN｜やめて良かった</b><span>自分の言葉</span></div><div id="win"></div></section><div class="hold" id="hold"><span></span><b id="holdTime"></b></div><button class="stop-btn" id="stop"></button><button class="allow-btn" id="allow"></button><button class="did-btn" id="did">条件外でやった / 食べた / 吸った</button></main>
<main id="resultView" class="view"><div class="result"><div class="big" id="re">✅</div><h2 id="rt"></h2><p id="rp"></p><div class="result-card" id="rs"></div><button class="home-btn" id="home">HOME</button></div></main>
<div class="sheet" id="sheet"><div class="sheet-card"><div class="sheet-head"><h3 id="sheetTitle">ログ</h3><button class="sheet-close" id="close">×</button></div><div id="edit"><div class="field"><label>追加WHY</label><textarea id="whyIn"></textarea></div><div class="field"><label>MY RULE｜追加条件（1行ずつ）</label><textarea id="ruleIn"></textarea></div><div class="field"><label>REAL WIN</label><textarea id="winIn"></textarea></div><button class="save-btn" id="save">保存</button></div><div class="logs"><h4>RECENT LOG</h4><div id="logList"></div></div></div></div>`;
var homeV=document.getElementById('homeView'),detailV=document.getElementById('detailView'),resultV=document.getElementById('resultView');
function show(v){[homeV,detailV,resultV].forEach(x=>x.classList.toggle('active',x===v));scrollTo(0,0)}
function renderHome(){var g=document.getElementById('urgeGrid');g.innerHTML='';ORDER.forEach(id=>{var c=C[id],b=document.createElement('button');b.className='urge'+((id==='alcohol'||id==='pork')?' faith':'');b.dataset.id=id;b.innerHTML='<span class="emoji">'+c.e+'</span><span><b>'+c.n+'</b><small>'+c.sub+'</small></span>';g.appendChild(b)});var s=stats();good.textContent=s.g;checks.textContent=s.t;rate.textContent=s.r===null?'—':s.r+'%';var x=logs().filter(x=>x.result==='stop'||x.result==='allow').slice(-1)[0];recent.innerHTML=x?'<b>WIN</b>　'+fd(x.ts)+' '+C[x.cat].e+' '+C[x.cat].n+(x.result==='allow'?'を条件内で選んだ。':'を止めた。'):'<b>WIN</b>　まだログなし。'}
function render(id){sel=id;var c=C[id],n=note(id);title.textContent=c.e+' '+c.n;impact.textContent=c.impact;desc.textContent=c.desc;faith.textContent=c.faith;rules.innerHTML='';var ex=n.rule?n.rule.split(/\n+/).map(x=>x.trim()).filter(Boolean):[];(c.rule||[]).concat(ex).forEach(t=>{var d=document.createElement('div');d.className='rule-item';d.textContent=t;rules.appendChild(d)});if(c.note){noteEl().hidden=false;noteEl().textContent=c.note}else noteEl().hidden=true;whys.innerHTML='';c.why.concat(n.why?[n.why]:[]).forEach(t=>{var d=document.createElement('div');d.className='reason';d.textContent=t;whys.appendChild(d)});loss.textContent=c.loss;ideal.textContent=c.ideal;stop.textContent=c.stop;winBlock.hidden=!n.win;if(n.win)win.textContent=n.win;updateHold();updateAllow();show(detailV)}
function noteEl(){return document.getElementById('note')}
function updateAllow(){if(!sel)return;var c=C[sel],b=allow,st=state;b.classList.remove('show');b.disabled=false;st.hidden=true;st.classList.remove('ready');if(!c.allow)return;b.textContent=c.allow;b.classList.add('show');if(c.after){var e=hend(sel);if(!e){b.disabled=true;st.hidden=false;st.textContent='まず24時間保留'}else if(e>Date.now()){b.disabled=true;st.hidden=false;st.textContent='24時間待機中'}else{st.hidden=false;st.classList.add('ready');st.textContent='24時間クリア'}}}
function updateHold(){clearInterval(timer);if(!sel)return;var c=C[sel],e=hend(sel);if(!e){hold.classList.remove('show');return}hold.classList.add('show');if(e<=Date.now()){hold.querySelector('span').textContent=c.after?'24時間クリア':'保留完了';holdTime.textContent='READY';updateAllow();return}hold.querySelector('span').textContent='すでに保留中';var tick=()=>{var l=e-Date.now();if(l<=0){clearInterval(timer);updateHold();updateAllow();return}var m=Math.ceil(l/60000);holdTime.textContent=m>=60?Math.ceil(m/60)+'h':m+'m'};tick();timer=setInterval(tick,30000)}
function log(type){if(!sel)return;var c=C[sel];if(type==='allow'&&c.after){var e=hend(sel);if(!e||e>Date.now())return}var a=logs();a.push({cat:sel,result:type,ts:Date.now()});wj(STORE.logs,a.slice(-300));if(type==='stop'&&c.hold){var h=holds(),e=hend(sel);if(!e||e<=Date.now()){h[sel]=Date.now()+c.hold;wj(STORE.holds,h)}}if(type==='allow'&&c.after){var h2=holds();delete h2[sel];wj(STORE.holds,h2)}var s=stats(sel);re.textContent=type==='stop'?'🛡️':type==='allow'?'✅':'↩️';rt.textContent=type==='stop'?'今回は止めた':type==='allow'?'条件内で選んだ':'条件外でやった';rp.textContent=type==='stop'?'禁止が目的やない。条件を見て、今回は止める方を選べた。':type==='allow'?'我慢だけが正解やない。先に決めた条件を通して選べた。':'全部失敗にはせん。条件外だった事だけ残して、次の1回で戻す。';rs.textContent=c.e+' '+c.n+'｜今月 '+s.g+' GOOD / '+s.t+' CHECKS'+(s.r===null?'':' · '+s.r+'%');show(resultV);renderHome()}
function renderLogs(){var t=logList,a=logs().slice(-25).reverse();t.innerHTML='';if(!a.length){t.innerHTML='<div class="empty">まだログなし</div>';return}a.forEach(x=>{var d=document.createElement('div');d.className='log';var m=x.result==='stop'?'🛡️':x.result==='allow'?'✅':'↩️';d.innerHTML='<span>'+m+' '+C[x.cat].e+' '+C[x.cat].n+(x.result==='allow'?' 条件内':'')+'</span><span>'+fd(x.ts)+'</span>';t.appendChild(d)})}
function openSheet(){sheetTitle.textContent=sel?C[sel].e+' '+C[sel].n:'Urgez LOG';edit.style.display=sel?'block':'none';if(sel){var n=note(sel);whyIn.value=n.why||'';ruleIn.value=n.rule||'';winIn.value=n.win||''}renderLogs();sheet.classList.add('show')}
function closeSheet(){sheet.classList.remove('show')}
urgeGrid.onclick=e=>{var b=e.target.closest('[data-id]');if(b)render(b.dataset.id)};back.onclick=()=>{sel=null;show(homeV);renderHome()};stop.onclick=()=>log('stop');allow.onclick=()=>log('allow');did.onclick=()=>log('did');home.onclick=()=>{sel=null;show(homeV);renderHome()};menuBtn.onclick=()=>{sel=null;openSheet()};detailMenu.onclick=openSheet;close.onclick=closeSheet;sheet.onclick=e=>{if(e.target===sheet)closeSheet()};save.onclick=()=>{if(!sel)return;var a=notes();a[sel]={why:whyIn.value.trim(),rule:ruleIn.value.trim(),win:winIn.value.trim()};wj(STORE.notes,a);closeSheet();render(sel)};document.addEventListener('visibilitychange',()=>{if(!document.hidden){renderHome();if(sel){updateHold();updateAllow()}}});
renderHome();
})();
